// Shared site data: intel categories. Imported by dx-categories.mjs, dx-chrome.mjs.
export const CATEGORIES = [
  {
    slug: 'protocol', name: 'Protocol', short: 'What to do, in order',
    title: 'UFO Encounter Protocols: What to Do',
    h1: 'What to do when something is in the sky.',
    desc: 'Step by step UFO encounter protocols for civilians: what to do if you see a UFO, how to film it, report it, protect your family and keep your evidence clean.',
    lede: 'Eleven files for the minutes that matter: what to do first, how to record it, who to tell, and what to keep out of your own hands.',
    lens: '/intel/images/ufo-sighting-1280.webp',
    start: 'what-to-do-if-you-see-a-ufo',
    answer: 'If you see something in the sky you cannot explain, stay where you are, start recording wide with the horizon in frame, note the time and direction, keep everyone at a distance, and write down what you saw before you talk about it. Every file in this category expands one of those steps.',
    why: 'Protocols are written for the version of you that has a pounding heart and ten seconds. They are short on purpose. If a step sounds boring, that is usually the step that keeps people safe and keeps the record usable.',
    pairs: ['field-guide', 'psychology'],
  },
  {
    slug: 'field-guide', name: 'Field guide', short: 'Satellite, drone or something else',
    title: 'How to Identify a UFO: Field Guide',
    h1: 'Is it a satellite, a drone, or something else?',
    desc: 'How to identify a UFO: tell Starlink trains, drones, planes, balloons and orbs apart from sightings that deserve a report, with the details investigators ask for.',
    lede: 'Most lights in the sky have ordinary explanations. These files teach you to rule them out fast, so the rare one that remains gets taken seriously.',
    lens: '/intel/images/starlink-vs-ufo-1280.webp',
    start: 'starlink-vs-ufo',
    answer: 'Most UFO sightings turn out to be satellites, aircraft, drones, balloons, planets or camera artifacts. To identify one, note its speed, direction, blinking pattern, sound and how long it stayed visible, then check each ordinary explanation in turn. What survives that check is worth reporting.',
    why: 'Misidentification is not an insult to witnesses. It is the first filter every serious investigator uses, and running it yourself is what makes your report credible when something does not fit.',
    pairs: ['protocol', 'public-record'],
  },
  {
    slug: 'psychology', name: 'Psychology', short: 'Fear, memory and silence',
    title: 'Psychology of UFO Encounters',
    h1: 'What the mind does with an impossible minute.',
    desc: 'The psychology of UFO encounters: why witnesses freeze, lose time, doubt their memory, stay silent or panic, and how to stay grounded if it happens to you.',
    lede: 'Fear, memory, silence and panic. Thirteen files on the part of every encounter that happens inside the witness.',
    lens: '/intel/images/ufo-psychology-1280.webp',
    start: 'psychology-of-ufo-encounters',
    answer: 'Strange events trigger the same stress response as any shock: people freeze, lose track of time, fill memory gaps without noticing and often stay silent afterward because they fear being mocked. Knowing these reactions in advance makes them easier to notice, name and manage.',
    why: 'None of these files diagnose anyone. If an experience is affecting your sleep, work or relationships, a qualified professional is the right next step, and the experiencer support file explains how to ask.',
    pairs: ['protocol', 'theory'],
  },
  {
    slug: 'species', name: 'Species', short: 'Reports and lore',
    title: 'Types of Aliens: Reported Species Files',
    h1: 'The beings people keep describing.',
    desc: 'Types of aliens described in encounter reports and lore, from Greys and Nordics to Reptilians and Mantids, with what witnesses report and what to do.',
    lede: 'Thirteen species files. Each one keeps what witnesses reported apart from what anyone has proven, and ends with what a civilian should do.',
    lens: '/assets/species-hangar/hangar-bg.webp',
    start: 'types-of-alien-species-ranked-threat',
    answer: 'The most commonly reported types in encounter lore are the Greys, Nordics, Reptilians, Mantids and Tall Whites, plus origin stories like the Anunnaki. None has been confirmed by any government or scientific body. These files treat them as reports and lore, and focus on what a civilian would actually do.',
    why: 'Species files are the most shared part of the archive and the easiest to get wrong. Every claim here is labeled as a report, a claim or a theory, because treating lore as fact is how people get played.',
    pairs: ['theory', 'protocol'],
  },
  {
    slug: 'public-record', name: 'Public record', short: 'Hearings, reports and files',
    title: 'UAP Public Record: Hearings and Files',
    h1: 'What governments have actually said.',
    desc: 'The UAP public record explained: congressional hearings, AARO and NASA reports, the National Archives records collection and famous cases, with dates and sources.',
    lede: 'Hearings, reports, archives and the famous cases, with the dates. Twelve files on what is on the record and what is not.',
    lens: '/intel/images/roswell-incident-1280.webp',
    start: 'uap-disclosure-act-2026-timeline',
    answer: 'Since 2023 the United States has held sworn congressional hearings on UAP, created a records collection at the National Archives, published reports from the Pentagon and NASA, and begun releasing batches of files. None of these official documents confirms contact or non-human technology.',
    why: 'This category is where the site is strictest. Each date links to its source, and anything we could only partly verify says so. If you find an error, tell us and we will fix it.',
    pairs: ['field-guide', 'theory'],
  },
  {
    slug: 'theory', name: 'Theory', short: 'Why the sky is quiet',
    title: 'Alien Theories Explained: Fermi to Dark Forest',
    h1: 'Why is the sky so quiet?',
    desc: 'Alien theories explained: the Fermi paradox, zoo hypothesis, dark forest, interdimensional and AI probe ideas, and what each would mean for first contact.',
    lede: 'The big models of why nobody has called, and what each one would mean for an ordinary person if contact did happen.',
    lens: '/intel/images/fermi-paradox-1280.webp',
    start: 'fermi-paradox-explained',
    answer: 'The universe looks old and large enough to hold other civilizations, yet we have no confirmed signal from any of them. That gap is the Fermi paradox, and theories like the zoo hypothesis, the dark forest and the rare Earth idea are competing explanations for it. None is proven.',
    why: 'Theories do not tell you what is out there. They tell you which kind of first contact to prepare for, which is why each file ends with the civilian takeaway rather than a verdict.',
    pairs: ['species', 'public-record'],
  },
];
export const CAT_BY_SLUG = Object.fromEntries(CATEGORIES.map(c => [c.slug, c]));
// hub data-cat values used on /intel/ map to these slugs
export const DATA_CAT = { protocol: 'protocol', 'field-guide': 'field-guide', psychology: 'psychology', species: 'species', record: 'public-record', theory: 'theory' };
