// Shared site data: intel categories. Imported by dx-categories.mjs, dx-chrome.mjs.
export const CATEGORIES = [
  {
    slug: 'protocol', name: 'Protocol', short: 'What to do, in order',
    title: 'UFO Encounter Protocol Files',
    h1: 'The UFO protocol files.',
    kicker: 'What to do when something is in the sky.',
    desc: 'Twelve civilian protocols for the minutes after a sighting: filming, reporting, a car being followed, a landing nearby, family roles and the kit.',
    lede: 'Stay where you are, record wide with the horizon in frame, note the time and direction, keep your distance and write it down before you talk. Twelve files expand those steps.',
    lens: '/intel/images/ufo-sighting-1280.webp',
    start: 'what-to-do-if-you-see-a-ufo',
    answer: 'If you see something in the sky you cannot explain, stay where you are, start recording wide with the horizon in frame, note the time and direction, keep everyone at a distance, and write down what you saw before you talk about it. Every file in this category expands one of those steps.',
    why: 'Protocols are written for the version of you that has a pounding heart and ten seconds. They are short on purpose. If a step sounds boring, that is usually the step that keeps people safe and keeps the record usable.',
    pairs: ['field-guide', 'psychology'],
  },
  {
    slug: 'field-guide', name: 'Field guide', short: 'Satellite, drone or something else',
    title: 'How to Identify a UFO: Field Guide',
    h1: 'How to identify a UFO: the field guide.',
    kicker: 'Is it a satellite, a drone, or something else?',
    desc: 'Most UFO sightings are satellites, aircraft, drones, balloons or planets. The checks that rule each one out, and what to report if a sighting survives.',
    lede: 'Most UFO sightings turn out to be satellites, aircraft, drones, balloons, planets or camera artifacts. Eleven files teach you to rule each one out fast, so the rare sighting that survives gets taken seriously.',
    lens: '/intel/images/starlink-vs-ufo-1280.webp',
    start: 'starlink-vs-ufo',
    answer: 'Most UFO sightings turn out to be satellites, aircraft, drones, balloons, planets or camera artifacts. To identify one, note its speed, direction, blinking pattern, sound and how long it stayed visible, then check each ordinary explanation in turn. What survives that check is worth reporting.',
    why: 'Misidentification is not an insult to witnesses. It is the first filter every serious investigator uses, and running it yourself is what makes your report credible when something does not fit.',
    pairs: ['protocol', 'public-record'],
  },
  {
    slug: 'psychology', name: 'Psychology', short: 'Fear, memory and silence',
    title: 'UFO Psychology Files: Fear, Memory and Belief',
    h1: 'The UFO psychology files.',
    kicker: 'What the mind does with an impossible minute.',
    desc: 'Freezing, missing time, unreliable memory, dreams, silence and panic are normal shock responses. Thirteen files on noticing them and staying grounded.',
    lede: 'Shock does predictable things: people freeze, lose track of time, fill memory gaps without noticing and stay silent for fear of mockery. Thirteen files name those reactions so you can notice and manage them.',
    lens: '/intel/images/ufo-psychology-1280.webp',
    start: 'psychology-of-ufo-encounters',
    answer: 'Strange events trigger the same stress response as any shock: people freeze, lose track of time, fill memory gaps without noticing and often stay silent afterward because they fear being mocked. Knowing these reactions in advance makes them easier to notice, name and manage.',
    why: 'None of these files diagnose anyone. If an experience is affecting your sleep, work or relationships, a qualified professional is the right next step, and the experiencer support file explains how to ask.',
    pairs: ['protocol', 'theory'],
  },
  {
    slug: 'species', name: 'Species', short: 'Reports and lore',
    title: 'Reported Alien Species Files',
    h1: 'The alien species files.',
    kicker: 'The beings people keep describing.',
    desc: 'No reported alien species has been confirmed. Greys, Nordics, Reptilians, Mantids and Tall Whites, kept apart from proof, each with a civilian protocol.',
    lede: 'None of the alien species people report has been confirmed by any government or scientific body. Thirteen files, from Greys and Nordics to Mantids and the Anunnaki, keep reports apart from proof and end with what a civilian should do.',
    lens: '/assets/species-hangar/hangar-bg.webp',
    start: 'types-of-alien-species-ranked-threat',
    answer: 'The most commonly reported types in encounter lore are the Greys, Nordics, Reptilians, Mantids and Tall Whites, plus origin stories like the Anunnaki. None has been confirmed by any government or scientific body. These files treat them as reports and lore, and focus on what a civilian would actually do.',
    why: 'Species files are the most shared part of the archive and the easiest to get wrong. Every claim here is labeled as a report, a claim or a theory, because treating lore as fact is how people get played.',
    pairs: ['theory', 'protocol'],
  },
  {
    slug: 'public-record', name: 'Public record', short: 'Hearings, reports and files',
    title: 'UAP Public Record: Hearings and Files',
    h1: 'The UAP public record.',
    kicker: 'What governments have actually said.',
    desc: 'No official UAP document confirms contact. The hearings, AARO and NASA reports, the National Archives collection and the 2026 releases, dated and sourced.',
    lede: 'No official document confirms contact or non-human technology. Since 2023 the United States has held sworn UAP hearings, opened a National Archives records collection, published Pentagon and NASA reports and begun releasing files.',
    lens: '/intel/images/roswell-incident-1280.webp',
    start: 'uap-disclosure-act-2026-timeline',
    answer: 'Since 2023 the United States has held sworn congressional hearings on UAP, created a records collection at the National Archives, published reports from the Pentagon and NASA, and begun releasing batches of files. None of these official documents confirms contact or non-human technology.',
    why: 'This category is where the site is strictest. Each date links to its source, and anything we could only partly verify says so. If you find an error, tell us and we will fix it.',
    pairs: ['field-guide', 'theory'],
  },
  {
    slug: 'theory', name: 'Theory', short: 'Why the sky is quiet',
    title: 'Alien Theories Explained: Fermi to Dark Forest',
    h1: 'The alien theory files.',
    kicker: 'Why is the sky so quiet?',
    desc: 'Nobody has called, and no theory says why for certain. The Fermi paradox, zoo hypothesis, Dark Forest and AI probes, each with its civilian lesson.',
    lede: 'Eight files on the big models of why nobody has called, from the Fermi paradox to the Dark Forest, and what each would mean for an ordinary person if contact did happen. None is proven.',
    lens: '/intel/images/fermi-paradox-1280.webp',
    start: 'fermi-paradox-explained',
    answer: 'The universe looks old and large enough to hold other civilizations, yet we have no confirmed signal from any of them. That gap is the Fermi paradox, and theories like the zoo hypothesis, the dark forest and the rare Earth idea are competing explanations for it. None is proven.',
    why: 'Theories do not tell you what is out there. They tell you which kind of first contact to prepare for, which is why each file ends with the civilian takeaway rather than a verdict.',
    pairs: ['species', 'public-record'],
  },
];
export const CAT_BY_SLUG = Object.fromEntries(CATEGORIES.map(c => [c.slug, c]));
// hub data-cat values used on /intel/ map to these slugs
export const DATA_CAT = { protocol: 'protocol', 'field-guide': 'field-guide', psychology: 'psychology', species: 'species', record: 'public-record', theory: 'theory' };
